@echo off
echo Creating Python environment...
conda create -n clearcounty-env python=3.11 --yes
echo Activating environment...
call conda activate clearcounty-env
echo Installing Python dependencies...
pip install -r requirements.txt
echo Setup is complete.
pause
